### PR TITLE
chore(deps): bump dependencies

### PR DESCRIPTION
**Pull request by ttbarnes**
## Introduction :pencil2:
- Dependabot flagged some dependency updates.

## Resolution :heavy_check_mark:
- Update dependencies.
- Remove `mysql2` package (EMS-3950)

### CODE REVIEW

**Review by Zainzzkk — DISMISSED** [review]
do we need to bump gov front end here as well? like DTFS

**Review by Zainzzkk — COMMENTED** [review]
and should this be into main or iterations-2?

**Comment by ttbarnes** [comment]
> do we need to bump gov front end here as well? like DTFS

No, EXIPS is already up to date. DTFS is many versions behind

**Comment by ttbarnes** [comment]
> and should this be into main or iterations-2?

It will be easier to keep this in `iterations-2`.

This branch will be the next release. It's very unlikely for us to push `main` to `production` with pure dependency updates.

By keeping dep updates in `iterations-2` it will make merging `main` => `iterations-2` or vice versa easier

**Comment by ttbarnes** [comment]
> > > and should this be into main or iterations-2?
> > 
> > 
> > It will be easier to keep this in `iterations-2`.
> > This branch will be the next release. It's very unlikely for us to push `main` to `production` with pure dependency updates.
> > By keeping dep updates in `iterations-2` it will make merging `main` => `iterations-2` or vice versa easier
> 
> The only issue is dependabot is set to main, and we are making the changes in iterations-2 and dependabot will not see that we've made the change @abhi-markan

Dependabot will only flag new package updates - if a package is updated in `main-iterations-2`, but not in `main`, dependabot will not create the same alert in `main`. There will be no additional dependabot PRs because we're updating in the iterations branch.

This branch should be very short lived.

In the previous iterations branch, we did dependabot updates in `main` instead of `iterations` and it caused several headaches RE merge conflicts and dependabot updates. Whilst this was occuring, `main` was never pushed to production with the dep updates so it was almost pointless _not_ doing it in the iterations branch.

**Review by Zainzzkk — APPROVED** [review]

**Pull request merged**
